id = "dockerfile"
name = "Dockerfile"
version = "0.1.0"
schema_version = 1
description = "Dockerfile support."
repository = "https://github.com/zed-extensions/dockerfile"
authors = ["d1y <chenhonzho@gmail.com>", "joshmeads <github@joshmeads.com>"]
themes = []
icon_themes = []
languages = ["languages/dockerfile"]
capabilities = []

[lib]
kind = "Rust"
version = "0.7.0"

[grammars.dockerfile]
repository = "https://github.com/camdencheek/tree-sitter-dockerfile"
rev = "868e44ce378deb68aac902a9db68ff82d2299dd0"

[language_servers.dockerfile-language-server]
language = "Dockerfile"
languages = []

[language_servers.dockerfile-language-server.language_ids]

[context_servers]

[slash_commands]

[indexed_docs_providers]

[debug_adapters.buildx-dockerfile]
schema_path = "./debug_adapter_schemas/buildx-dockerfile.json"
