id = "material-icon-theme"
name = "Material Icon Theme"
version = "1.3.1"
schema_version = 1
description = "Material Design icons."
repository = "https://github.com/zed-extensions/material-icon-theme"
authors = ["Zed Industries <support@zed.dev>"]
themes = []
icon_themes = ["icon_themes/material-icon-theme.json"]
languages = []
capabilities = []

[lib]

[grammars]

[language_servers]

[context_servers]

[agent_servers]

[slash_commands]
