id = "csv"
name = "CSV"
version = "0.0.3"
schema_version = 1
description = "CSV language support."
repository = "https://github.com/huacnlee/zed-csv"
authors = ["Jason Lee <huacnlee@gmail.com>"]
themes = []
icon_themes = []
languages = ["languages/csv"]
capabilities = []

[lib]
kind = "Rust"
version = "0.0.4"

[grammars.csv]
repository = "https://github.com/arnau/tree-sitter-csv"
rev = "4b25b5d745f9462e54b781e3d7798b8e0a4db703"

[language_servers]

[context_servers]

[slash_commands]

[indexed_docs_providers]
